#1466 Implementation of the SplitButton component
flow-buddy/bappo-open pull request #76
Opened 2021-02-23 10:24 UTC by emil-bappo

- Added a SplitButton component which allows additional actions to be executed using a popup menu
- The SplitButton accepts a type prop (`primary`, `secondary`, `destructive`)
- The primary button's click event is handled by the `onButtonPress` prop
- The Menu component was changed to make the `close` and `open` methods available to the trigger. This allows components handling `onPress` to be used as triggers (for example the `Button` component)

2021-02-28 09:01 UTC, Jonathanliu525 requested changes
Hi Emil, good job. A very clean and fancy code you write. I found some typo and gave some suggestions. Let me know if that works

2021-02-28 09:01 UTC, Jonathanliu525 commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/Menu/examples/example.js
>        <Menu.Item icon="home" onPress={() => console.log('you pressed Home')}>
Hi Email, for the actions, it could be better if we all use alert. As console.log need people to open devtools

2021-02-28 09:01 UTC, Jonathanliu525 commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropActions.js
> +export default ButtonActionsExample;
I think we the export default may need to have the same name with file. In this case, I think ButtonActionsExample.js could be a better name

2021-02-28 09:01 UTC, Jonathanliu525 commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropType.js
> +      onButtonPress={() => alert('You pressed the primary button')}
Is that a typo here?  'You pressed the secondary button'

2021-02-28 09:01 UTC, Jonathanliu525 commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropType.js
> +      onButtonPress={() => alert('You pressed the primary button')}
Is that a typo here?  'You pressed the destructive button'

2021-02-28 09:01 UTC, Jonathanliu525 commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropType.js
> +    </SplitButton>
It could be looks nice if you add the tertiary button, as you have already add the primary, secondary and destructive

2021-03-01 06:38 UTC, emil-bappo commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/Menu/examples/example.js
>        <Menu.Item icon="home" onPress={() => console.log('you pressed Home')}>
Hi Jon, thanks, I've change all the console.log statements to alert

2021-03-01 06:39 UTC, emil-bappo commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropActions.js
> +export default ButtonActionsExample;
I've changed the files to the respective default export name, thanks for the suggestion

2021-03-01 08:12 UTC, emil-bappo commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropType.js
> +      onButtonPress={() => alert('You pressed the primary button')}
Hi Jon, the `primary` refers to the primary button of the split button component (the button that is displayed to the left of the menu trigger (down arrow icon) and not the type of button. I think I should change it to 'You pressed the primary button of the SplitButton with secondary type' to be less confusing?

2021-03-01 08:13 UTC, emil-bappo commented on packages/bappo-components/storybook/storybook-native/storybook/stories/2-components/SplitButton/examples/PropType.js
> +    </SplitButton>
Thanks for the suggestion! I've added an example for the tertiary type too.

2021-03-01 23:40 UTC, merged